cmw-array = cmw-array-cbor / cmw-array-json

cmw-array-cbor = [ type, bytes ]

cmw-array-json = [ type, base64-string ]

type = coap-content-format / media-type
coap-content-format = uint .size 2
media-type = text .abnf ("Content-Type" .cat Content-Type-ABNF)

base64-string = text .regexp "[A-Za-z0-9_-]+"
